### ISSUE TITLE
How do I use this???

### ISSUE THREAD

**Issue by brappuh** [megadose/toutatis#102]
Im able to use pip to install it but when I try to run the Python3 command, it says I don't have permission or something and it can't continue, I'm literally signed in as the Administrator, I took over the actual Administrator account long ago.

Someone please help me figure out how to use this program. It's super important to me. It's so important to me, I really need to use it.

**Comment by 4ngel6uard** [comment]
just use sudo on linux

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5
