### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by chadofork** [megadose/toutatis#11]
I'm getting this error after introducing the instagram username and sessionid:
![ERROR](https://user-images.githubusercontent.com/87623662/126086408-65870bf2-cc17-45ce-90c7-f9de7c53f2c2.png)

I'm running toutatis on my laptop via termux and BlueStacks.

**Comment by megadose** [comment]
![image](https://user-images.githubusercontent.com/51822495/126194312-42ee408c-44f4-4c15-befa-5d54643c0ee6.png)
