### ISSUE TITLE
KeyError: 'full_name'

### ISSUE THREAD

**Issue by httpanand** [megadose/toutatis#32]
```
Programs\Python\Python310\lib\site-packages\toutatis\core.py", line 87, in main
    print("Full Name              : "+infos["full_name"]+" | userID : "+infos["userID"])
KeyError: 'full_name'
```

**Comment by deltabravozulu** [comment]
Same

**Comment by deltabravozulu** [comment]
Nevermind. The cause is an incorrect sessionid. It can be URL encoded like `1802993369%3A8cfThet9t1HQSD%3A12` or presented as a string like `1802993369:8cfThet9t1HQSD:12`. You might have also grabbed the wrong sessionid.

**Comment by httpanand** [comment]
> Nevermind. The cause is an incorrect sessionid. It can be URL encoded like `1802993369%3A8cfThet9t1HQSD%3A12` or presented as a string like `1802993369:8cfThet9t1HQSD:12`. You might have also grabbed the wrong sessionid.

no my session is correct. i have used toutatis before and not its not working

**Comment by Bazili028** [comment]
Was the same problem
Solved by update sessionid

**Comment by Abdelzero** [comment]
How can I update the sessionid?
