### ISSUE TITLE
Toutatis didn't work properly untill 11th of May...

### ISSUE THREAD

**Issue by nonvegshayar** [megadose/toutatis#33]
Hello **Toutatis GitHub Tool Developer Team**...

Your Toutatis software should not be work properly...

Now it's unable to find out last two digit of any instagram account phone number or email...

I would like to say that please fix it.... because its one of my favorate , best and unbeliveable tool in github related to instagram account information gathering tool...I haven't seen ever this kind of similar tool on github...

Thank You

**Comment by novitae** [comment]
@nonvegshayar https://github.com/megadose/toutatis/issues/35#issuecomment-1137766073
