### ISSUE TITLE
Toutatis is no more working

### ISSUE THREAD

**Issue by AsadAhmad-1337** [megadose/toutatis#37]
<img width="960" alt="error" src="https://user-images.githubusercontent.com/96720304/177016394-bae7ceb2-c638-41b3-9d6d-bd8fbcf32b83.PNG">

It was running fine few months ago when i used this tool but now it's not working.what i ve noticed that  instagram session id structure and its length is changed.

**Comment by StarLord42** [comment]
Hello @AsadAhmad-1337 

Try to connect your computer to your smartphone (Hotspot). It works for me as a workaround.

Kind regards

**Comment by AsadAhmad-1337** [comment]
<img width="817" alt="4g toutatis" src="https://user-images.githubusercontent.com/96720304/177055158-7950bc6b-96b1-4bb8-b0ac-6fd91e844632.PNG">
> Hello @AsadAhmad-1337
> 
> Try to connect your computer to your smartphone (Hotspot). It works for me as a workaround.
> 
> Kind regards

Hello @StarLord42 thanks for your reply but problem is still not resolved yet even after i connect my pc with smartphone hotspot check out the attached screenshot

**Comment by AsadAhmad-1337** [comment]
@megadose kindly check the errors thanks
