### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Axelu2020** [megadose/toutatis#4]
The script was working all great but after a while I kept getting key errors
> Traceback (most recent call last):
  File "testu.py", line 2, in <module>
    print(extractEmail("starbucks", "sessionId (censored)"))
  File "/usr/lib/python3.8/site-packages/toutatis-1.21-py3.8.egg/toutatis/core.py", line 39, in extractEmail
  File "/usr/lib/python3.8/site-packages/toutatis-1.21-py3.8.egg/toutatis/core.py", line 17, in getInfo
  File "/usr/lib/python3.8/site-packages/toutatis-1.21-py3.8.egg/toutatis/core.py", line 13, in getUserId
KeyError: 'logging_page_id'

I think this is probably an api limit, just wanting to make sure tho.

Ps: thank ya for making toutatis. It's really helpful

**Comment by Hydrenez** [comment]
I'm having the same issue, but it says KeyError : 'Full_name'

**Comment by megadose** [comment]
if you don't give the user who poses the problem I can't answer your problem

**Comment by megadose** [comment]
For me it works
Informations about : starbucks
Full Name : Starbucks Coffee ☕ userID : 1034466
Verified : True Is buisness Acount : True
Is private Account : False
Follower : 18247408 Following : 3878
Number of posts : 2105
Number of tag in posts : 0
External url : https://starbucks.app.link/iccb
IGTV posts : 1
Biography : Not found
Public Email : info@starbucks.com
Public Phone number : 18007827282
Profile Picture : https://scontent-frx5-1.cdninstagram.com/v/CENSORED
