### ISSUE TITLE
User not found or rate limit

### ISSUE THREAD

**Issue by andre-santos1** [megadose/toutatis#41]
Wherever I do I keep receiving "User not found or rate limite"

I tried different Instagram targets, different sessionIDs and different internet connectios (cable and cell phone hot spot)

**Comment by Andrejki** [comment]
> 

Having the same problem. 
Tried furthermore the different targets with public and private accounts - the same. 
I don t get it.

**Comment by caribmorn** [comment]
same for me.

**Comment by Compr0mzd** [comment]
same

**Comment by Andrejki** [comment]
Hi. No solution to this?
Has instagram changed it s API or something else is the problem?

Best regards

**Comment by luke-sanger** [comment]
also getting this error

**Comment by spxwnmc** [comment]
This problem only occurs with the version installed from pip3. I recommend removing this version ( `pip3 uninstall toutatis` ) and installing from the repo itself. After doing this, everything works fine. I hope it works for you
````
git clone https://github.com/megadose/toutatis.git
cd toutatis/
python3 setup.py install
````

**Comment by osintgithub** [comment]
> This problem only occurs with the version installed from pip3. I recommend removing this version ( `pip3 uninstall toutatis` ) and installing from the repo itself. After doing this, everything works fine. I hope it works for you
> 
> ```
> git clone https://github.com/megadose/toutatis.git
> cd toutatis/
> python3 setup.py install
> ```

This worked for me, but will note that it's still not grabbing the obfuscated email or phone number except the end (only @gmail.com or @yahoo.com).

**Comment by megadose** [comment]
https://pypi.org/project/toutatis/1.3/
