### ISSUE TITLE
User not found and rate limit

### ISSUE THREAD

**Issue by sir-Five5** [megadose/toutatis#48]
First couple of times was working perfectly fine but now the only thing it shows is "user not found and rate limit"

**Comment by chirazcheikha** [comment]
Same here

**Comment by craqpter** [comment]
same problem User not found or rate limit

**Comment by C4l1b3r** [comment]
Same response

**Comment by Nex026** [comment]
guys to fix this **error**, follow these steps:

`pip uninstall toutatis`
**then**
`pip install toutatis==1.3`

I hope this helps :D
