### ISSUE TITLE
User not found or rate limit

### ISSUE THREAD

**Issue by ahsentekdemir** [megadose/toutatis#59]
I want to test this project but its not working i think instagram api stuffs has changed any progress on this project?

**Comment by louisgenie** [comment]
Same problem too!

**Comment by andre-santos1** [comment]
Same

**Comment by Bears9355** [comment]
Same as well

**Comment by girodrop** [comment]
Same here

**Comment by GannicusTheGreat** [comment]
Same "KeyError: 'logging_page_id'"
