### ISSUE TITLE
QUESTION ABOUT EMAILS AND PHONE NUMBERS

### ISSUE THREAD

**Issue by slaishxd** [megadose/toutatis#6]
Hey, is there some way to get the entire mail or phone number? Or it will always show them obfuscated?

**Comment by megadose** [comment]
It is sometimes possible but it depends on the account, allatis get the full email and phone number when possible
![image](https://user-images.githubusercontent.com/51822495/112858797-82532e80-90b2-11eb-8cc1-1951defca907.png)

**Comment by axakrem1** [comment]
i tried it many times but it doesnt work ! thanks for your hard work
