### ISSUE TITLE
help, user not found

### ISSUE THREAD

**Issue by dudeskii** [megadose/toutatis#66]
i try to put username and session id, i looked up some tutorials but couldn't find anything to fix this problem...help. all it said was user not found and rate something something
![usernotfound](https://user-images.githubusercontent.com/120918273/208292558-7343e45f-d08b-4e10-ba06-9a34331d2eb6.jpg)

**Comment by KyozuFR** [comment]
same problem

**Comment by mayurparmar42** [comment]
Same problem..

**Comment by Lucasbigbox** [comment]
same
