### ISSUE TITLE
User not found or rate limit

### ISSUE THREAD

**Issue by 47k** [megadose/toutatis#73]
I got this everytime - I think it's not working anymore

**Comment by tupski** [comment]
Have you changed your session ID by switching to a different account? Maybe the issue is with your current account. Try using a different one.

I have tried this tool and it works fine, but the results (phone numbers and emails) are obfuscated

**Comment by 47k** [comment]
First i tried with my account on my machine and then with a seperate machine with a fresh account - both the same

**Comment by yangdaddy** [comment]
KeyError: 'logging_page_id'
hi,what does this error mean?

**Comment by axiomgraph** [comment]
uninstall toutatis then use
pip install toutatis==1.3

**Comment by maro14** [comment]
> uninstall toutatis then use pip install toutatis==1.3

i was used to this and it works but I can't get the email and phone number

**Comment by se7enge** [comment]
> uninstall toutatis then use pip install toutatis==1.3

This worked for me. @axiomgraph I would be interested if you could elaborate as to why it works when installing this way and not the default way (without specifying version) though?

**Comment by o2tto** [comment]
> > uninstall toutatis then use pip install toutatis==1.3
> 
> This worked for me. @axiomgraph I would be interested if you could elaborate as to why it works when installing this way and not the default way (without specifying version) though?

Hi, idk how to uninstall toutatis, i'm on the same things rate limit, can you tell me how to ? tysm

**Comment by axiomgraph** [comment]
> > > uninstall toutatis then use pip install toutatis==1.3
> > 
> > 
> > This worked for me. @axiomgraph I would be interested if you could elaborate as to why it works when installing this way and not the default way (without specifying version) though?
> 
> Hi, idk how to uninstall toutatis, i'm on the same things rate limit, can you tell me how to ? tysm

https://pip.pypa.io/en/stable/cli/pip_uninstall/ read this

**Comment by liquidberny** [comment]
> uninstall toutatis then use pip install toutatis==1.3

After doing this and executing a the program in termal I get this :
`Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/toutatis/core.py", line 85, in main
    if not infos["user"]:
           ~~~~~^^^^^^^^
KeyError: 'user'`
Is toutatis really working? I've seen that the repo still has merges

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5
