### ISSUE TITLE
KeyError: full name and bin/toutatis line 33 error

### ISSUE THREAD

**Issue by stefanobabyy777** [megadose/toutatis#83]
Can someone help me how to fix this
Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.26', 'console_scripts', 'toutatis')())
  File "/usr/local/lib/python3.9/dist-packages/toutatis-1.26-py3.9.egg/toutatis/core.py", line 92, in main
KeyError: 'full_name'

**Comment by EliteGreyIT67** [comment]
The error message `KeyError: 'full_name'` means that the Python code is trying to access a key called `full_name` in a dictionary or DataFrame, but the key does not exist.

In the case of the code you provided, the error is occurring on line 92 of the `main()` function in the `toutatis/core.py` file. This line of code is trying to access the `full_name` column of the DataFrame, but the DataFrame does not have a `full_name` column.

To fix this error, you need to make sure that the DataFrame has a `full_name` column before trying to access it. You can do this by adding a `full_name` column to the DataFrame, or by checking to see if the `full_name` column exists before trying to access it.

Here is an example of how to fix the error:

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Create a DataFrame
df = pd.DataFrame({'full_name': ['Alice', 'Bob', 'Carol'], 'age': [25, 30, 35]})

# Check to see if the DataFrame has a `full_name` column
if 'full_name' not in df.columns:
    # Add a `full_name` column to the DataFrame
    df['full_name'] = ['Alice', 'Bob', 'Carol']

# Print the DataFrame
print(df)
```

This code will check to see if the DataFrame has a `full_name` column. If it does not have a `full_name` column, the code will add a `full_name` column to the DataFrame. Once the DataFrame has a `full_name` column, the code will print the DataFrame.

When you run this code, you will see the following output:

```
  full_name  age
0  Alice     25
1  Bob       30
2  Carol     35
```

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5
