### ISSUE TITLE
Rate limit or user not found error

### ISSUE THREAD

**Issue by rememberfloky** [megadose/toutatis#84]

**Comment by kamuluzo** [comment]
i have the same problem. I get the same error 
(toutatis -s 15057125558%3AcGJsyouMCrpuFa%3A13%3Axxxxxxxxxxxxxxxxxxxxxxxx -u osint.techniques
User not found or rate limit)

although the user exists (see at https://www.instagram.com/osint.techniques/)

**Comment by Alirezaghandchi53** [comment]
i have same problem, waiting for fixing the issue>
