### ISSUE TITLE
Am i running this tool correctly i am getting this error please help me 

### ISSUE THREAD

**Issue by xico0r** [megadose/toutatis#85]
![tool](https://github.com/megadose/toutatis/assets/145839404/ada86734-47a0-4fb0-aa77-a9fda5a53893)

**Comment by CrazyKoustik** [comment]
You have to pass your sessionid for your instagram account. You can get it by viewing your cookies, select the relative ones for your instagram account (you must be logged first) and search for the sessionid keyword. This sgould look like a long random string.

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5

**Comment by karrobinabi-cpu** [comment]
i want to check one profiles email and number

**Comment by zeyaidaltaf5-max** [comment]
Hello, I installed Toutatis on Termux. I would like to know what public profile information this tool can retrieve. Does it only show publicly available data? Thank you.

**Comment by zeyaidaltaf5-max** [comment]
Moannnnnn.a I need this account information

**Comment by sahilas8888-ctrl** [comment]
salman_khan_64_k   ...  I need this account information like email id and phone number

**Comment by vikax000089-max** [comment]
quail.72569793 is id ka details chahiye
