### ISSUE TITLE
My suggest please add new feature like spy message

### ISSUE THREAD

**Issue by AnandaRauf** [megadose/toutatis#91]
Dear Developer toutis,

Good morning, afternoon,and evening.

I have a suggest for your projects very good potential in Cybersecurity, my suggest is add new feature spy message.

If you add my suggest,I will create the newest and most complete tools library.

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5
