### ISSUE TITLE
Help with Key error: following_tag_count

### ISSUE THREAD

**Issue by CronosCtrl** [megadose/toutatis#92]
Hi, every account i lookup show this. I don't get email adress associated. Any help please?? 

Informations about     : amazon
userID                 : 845447128
Full Name              : Amazon
Verified               : True | Is buisness Account : True
Is private Account     : False
Follower               : 4567984 | Following : 66
Number of posts        : 2678

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.26', 'console_scripts', 'toutatis')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/toutatis-1.26-py3.11.egg/toutatis/core.py", line 97, in main
KeyError: 'following_tag_count'

**Comment by CrazyKoustik** [comment]
I have the same problem...

**Comment by williamlaurent** [comment]
I have the same problem too, I dont know how to fix it

**Comment by Crimson360** [comment]
i found an issue that MIGHT be related to this,im really not sure at all.
argparse keeps deleting automatically after installing it.So we can pip install it as many times as we want,and it will say it downloaded it.
![IMG_0862](https://github.com/megadose/toutatis/assets/149340042/8eeac7b9-a183-4e11-9dca-437483ef726e)

**Comment by williamlaurent** [comment]
> i found an issue that MIGHT be related to this,im really not sure at all. argparse keeps deleting automatically after installing it.So we can pip install it as many times as we want,and it will say it downloaded it. ![IMG_0862](https://private-user-images.githubusercontent.com/149340042/295032687-8eeac7b9-a183-4e11-9dca-437483ef726e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NzE1NzcsIm5iZiI6MTcwNDc3MTI3NywicGF0aCI6Ii8xNDkzNDAwNDIvMjk1MDMyNjg3LThlZWFjN2I5LWExODMtNGUxMS05ZGNhLTQzNzQ4M2VmNzI2ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwMzM0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWI2OGExMzU1NmU3ODcyOGJmMzk5NTBiYWIyZTdkNGZlZmFhMGNhNzQ2YWZkMDc4Y2QyODliM2EyZDFlM2RmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.89-0NU6szbmfR_4cNlVRGCex1zHandGlDattQ8y9mWQ)

i will try install it. thanks

**Comment by Skayara** [comment]
Same for me, the solution about argparse didn't work :(

**Comment by Crimson360** [comment]
Also btw,i forgot to mention something,sorry for my dumbness.
Some modules are deprecated and thus,don't work correctly,and might be a part of the problem

**Comment by ValentineGilles** [comment]
Same for me :(

**Comment by Crimson360** [comment]
I just found something.My great dumbness made this slow.Argparse doesn't download because of the python version.It is not supported above 3.4 And i have the 3.7 version🤦‍♂️

**Comment by katasandi1234** [comment]
no fix till now?
