### ISSUE TITLE
KeyError: 'user' can someone help me please 

### ISSUE THREAD

**Issue by crz81** [megadose/toutatis#93]
i got allways an Error KeyError: 'user' syntax: toutatis -u XXXXXXXXXX -s XXXXXXXXXXXXXXXXXXXXXXX 

![Screenshot from 2024-02-11 13-48-54](https://github.com/megadose/toutatis/assets/89300716/cb45e484-5cc8-4e9a-917d-f1e4ceb4a7e4)

**Comment by katasandi1234** [comment]
evev me i got the same error, pls if you see a fix post here

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5
