### ISSUE TITLE
User not found or rate limit

### ISSUE THREAD

**Issue by ps81frt** [megadose/toutatis#94]
No work for me always that
- User not found or rate limit

and i test on my account.
Any idea ?

Par toutatis !!!! :)

**Comment by Scunl** [comment]
i've the same but idk how to solve it

**Comment by albotroz** [comment]
nope, doesn't work

**Comment by Scunl** [comment]
i made it work but idk how to pull request, i tried to contact the owner but no answer

**Comment by h1dd3nr34p3r** [comment]
Hey @Scunl  I hardcoded the session id in the main file and still keep getting rate limit error. What did you do to fix the problem? Would mean alot if you could help.

**Comment by Scunl** [comment]
Hello, sorry i havent seen ur message. I can give you my code if u want add me on discord: scunl

**Comment by Scunl** [comment]
https://github.com/megadose/toutatis/pull/97 I finally did a PR @h1dd3nr34p3r

**Comment by FL3MM3** [comment]
> Hello, sorry i havent seen ur message. I can give you my code if u want add me on discord: scunl @h1dd3nr34p3r

Can you give me your code please ?

**Comment by ps81frt** [comment]
> > Hello, sorry i havent seen ur message. I can give you my code if u want add me on discord: scunl @h1dd3nr34p3r
> 
> Can you give me your code please ?

see here [https://github.com/megadose/toutatis/pull/97#issue-2190264943](url)

**Comment by h1dd3nr34p3r** [comment]
Hey bro, sorry yeah i'll add on discord if you still have the updated code?

**Comment by h1dd3nr34p3r** [comment]
> > Hello, sorry i havent seen ur message. I can give you my code if u want add me on discord: scunl @h1dd3nr34p3r
> 
> Can you give me your code please ?

Hey sorry for late reply, even with what I did it still comes up with rate error. I think instagram probably flags the tool in some way.

**Comment by h1dd3nr34p3r** [comment]
> #97 I finally did a PR @h1dd3nr34p3r

Hey, if you could update the repo that would be much appreciated.

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5
