### ISSUE TITLE
what is instagramsessionid?

### ISSUE THREAD

**Issue by loading-tech** [megadose/toutatis#96]

**Comment by Scunl** [comment]
u can find it here: https://commentpicker.com/instagram-user-id.php

**Comment by Creepy2e** [comment]
> u can find it here: https://commentpicker.com/instagram-user-id.php

usage: toutatis [-h] -s SESSIONID -u USERNAME
toutatis: error: unrecognized arguments: -i 54158219241

**Comment by Scunl** [comment]
did you install toutatis with pip ? @Creepy2e

**Comment by Creepy2e** [comment]
> did you install toutatis with pip ? @Creepy2e
Yes

**Comment by Creepy2e** [comment]
> did you install toutatis with pip ? @Creepy2e

pip install toutatis
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/toutatis-1.26-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/pycountry-23.12.11-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: toutatis in /usr/local/lib/python3.11/dist-packages/toutatis-1.26-py3.11.egg (1.26)
Collecting argparse (from toutatis)
  Using cached argparse-1.4.0-py2.py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: phonenumbers in /usr/lib/python3/dist-packages (from toutatis) (8.12.57)
Requirement already satisfied: pycountry in /usr/local/lib/python3.11/dist-packages/pycountry-23.12.11-py3.11.egg (from toutatis) (23.12.11)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from toutatis) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3/dist-packages (from requests->toutatis) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->toutatis) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->toutatis) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->toutatis) (2022.9.24)
Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Installing collected packages: argparse
Successfully installed argparse-1.4.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv                         



when i use toutatis -s 54103496275%3AHC6SGRNfFMGdTU**************** -u niw*****
is comming this message: User not found or rate limit 

and when i use it with -i its comming this: 

 usage: toutatis [-h] -s SESSIONID -u USERNAME
toutatis: error: unrecognized arguments: -i 54158219241

**Comment by Scunl** [comment]
that mean ur Toutatis is installed inside the folder where all libraries are installed. So u still have the original version. U need to locate the file where toutatis is installed, drag and drop my core and init.py inside the folder and everything should work

**Comment by Creepy2e** [comment]
> that mean ur Toutatis is installed inside the folder where all libraries are installed. So u still have the original version. U need to locate the file where toutatis is installed, drag and drop my core and init.py inside the folder and everything should work

where is your core and init.py where can i find it?

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5

**Comment by airspeedhacker** [comment]
what is username,instagramsessionid and  instagramID

**Comment by mohdfaruque62-cpu** [comment]
jissu_vlog_

**Comment by dnadd5952-sys** [comment]
valid_ig887
