### ISSUE TITLE
'toutatis' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Dune808** [megadose/toutatis#98]
Downloaded the pip through Windows terminal, when I ran it I got 

toutatis : The term 'toutatis' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ toutatis -u USERNAME -s SESSIONID
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (toutatis:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Obviously I used the right username and session ID, I'm just wondering what else I could do. Very basic level knowledge of windows terminal btw.

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5
