### ISSUE TITLE
Getting this error: KeyError: user

### ISSUE THREAD

**Issue by hunterbidens3rdlaptop** [megadose/toutatis#99]
RequestsDependencyWarning: urllib3 (2.2.1) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/local/bin/toutatis", line 33, in <module>
    sys.exit(load_entry_point('toutatis==1.26', 'console_scripts', 'toutatis')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/toutatis/core.py", line 85, in main
    if not infos["user"]:
           ~~~~~^^^^^^^^
KeyError: 'user'

**Comment by megadose** [comment]
https://github.com/megadose/toutatis/commit/22a59c0984fd17d5e01cdb57669ec527b2c6b3d5

**Comment by RiteshSec** [comment]
I have reinstalled the tool using pip, pip3 and the setup.py by cloning the repo. (The setup.py code is the same as the above code)

I am still getting the error when I try to run the tool. Please let me know how we can resolve this issue. 

![image](https://github.com/user-attachments/assets/91cc0f50-7896-4572-a7bd-88d3ff463325)
